### ISSUE TITLE
Plan the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by mattdavis0351** [mattdavis0351/github-for-everyone#1]
This project is going to be great :rocket: but before we open it up to the public we need to setup some guidelines for external contributions. 

@brooksseahorn What do you think about this :bulb: idea?

**Comment by brooksseahorn** [comment]
@mattdavis0351 ....awful!!! 🗑️

**Comment by mattdavis0351** [comment]
@brooksseahorn Great, I've added this to the project board, after break let's triage it!
